name: shell commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: action/checkout@v3
        - name: echo string
          run: echo "hello"
        - name: multiline script
           run: |
                node -v
                pwd